// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TutoringPlatform.Data;

#nullable disable

namespace TutoringPlatform.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527081736_FixIsRecurringTypo")]
    partial class FixIsRecurringTypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TutoringPlatform.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int?>("RemainingLessons")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TutorAvailabilityId")
                        .HasColumnType("integer");

                    b.Property<int>("TutoringAdId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorAvailabilityId");

                    b.HasIndex("TutoringAdId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("TutoringPlatform.Models.TutorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("TutoringAdId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TutoringAdId");

                    b.ToTable("TutorAvailabilities");
                });

            modelBuilder.Entity("TutoringPlatform.Models.TutoringAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TutorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TutoringAds");
                });

            modelBuilder.Entity("TutoringPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TutoringPlatform.Models.Lesson", b =>
                {
                    b.HasOne("TutoringPlatform.Models.User", "Student")
                        .WithMany("BookedLessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringPlatform.Models.TutorAvailability", "TutorAvailability")
                        .WithMany("Lessons")
                        .HasForeignKey("TutorAvailabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringPlatform.Models.TutoringAd", "TutoringAd")
                        .WithMany("Lessons")
                        .HasForeignKey("TutoringAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TutorAvailability");

                    b.Navigation("TutoringAd");
                });

            modelBuilder.Entity("TutoringPlatform.Models.TutorAvailability", b =>
                {
                    b.HasOne("TutoringPlatform.Models.TutoringAd", "TutoringAd")
                        .WithMany("TutorAvailabilities")
                        .HasForeignKey("TutoringAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TutoringAd");
                });

            modelBuilder.Entity("TutoringPlatform.Models.TutoringAd", b =>
                {
                    b.HasOne("TutoringPlatform.Models.User", "Tutor")
                        .WithMany("TutoringAds")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("TutoringPlatform.Models.TutorAvailability", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TutoringPlatform.Models.TutoringAd", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("TutorAvailabilities");
                });

            modelBuilder.Entity("TutoringPlatform.Models.User", b =>
                {
                    b.Navigation("BookedLessons");

                    b.Navigation("TutoringAds");
                });
#pragma warning restore 612, 618
        }
    }
}
